apiVersion: v1
kind: ConfigMap
metadata:
  name: userdb-config
data:
  userdb-url: userdb-service:5250
  userdb-user: User1 ##encoding to base 64 and decoding in the app does not work
  userdb-password: Adminpw ##encoding to base 64 and decoding in the app does not work
